version: "3.6"

services:
  db:
    container_name: empchat_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=empchat_user
      - POSTGRES_PASSWORD=manoszar
    ports:
    - "8888:5432"
    volumes:
    - /home/manzar/projects/emp_chat_survey/postgresdb/data:/var/lib/postgresql/data
    - /home/manzar/projects/emp_chat_survey/postgresdb/init.sql:/docker-entrypoint-initdb.d/initdb.sql

    
    
networks:
    default:
        external:
            name: manos_network
